# Generated by Django 5.1 on 2024-09-21 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
        ('predios', '0001_initial'),
        ('salas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universidade', models.CharField(default='UFRPE', max_length=50)),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=50)),
                ('datahora_inicio', models.DateTimeField()),
                ('datahora_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Em análise', max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacao', to='departamentos.departamento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacao', to=settings.AUTH_USER_MODEL)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacao', to='predios.predio')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacao', to='salas.sala')),
            ],
        ),
    ]
